### ISSUE TITLE
X axis 0  in ListPlot is wrong

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1436]
In 
```
ListPlot[Table[n ^ 2, {n, 10}]]
```

(and others)  the dots for the data is misaligned from the 0 or the tick marks of the Y axis.

@TiagoCavalcanteTrindade is this something you'd be interested in?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky #1428 should fix this, it was merged, but I saw [here](https://github.com/mathics/Mathics/blob/master/mathics/format/svg.py#L274) that its change is not applied 🤔.

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade Thanks for the investigation and information. #1437 adds an additional commit we don't want right now  Commit  2de55249 adds the #1428 back in. But this doesn't fix the problem.

**Comment by TiagoCavalcanteTrindade** [comment]
> #1437 adds an additional commit we don't want right now.

Sorry, I think it was my mistake in rebasing.

**Comment by rocky** [comment]
> > #1437 adds an additional commit we don't want right now.
> 
> Sorry, I think it was my mistake in rebasing.

np. 

> 
> > But this doesn't fix the problem.
> 
> Strange, I'll look at it.

Many thanks.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky the same function is being called by x and y tick numbers. The align of y must be to the right, while the align of the x must be to the center.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky that function is added to the class by a `add_conversion_fn`, and I don't see how it's called latter.

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade  Add print statements in the function. 

Personally I do this: 

```
pip install trepan3k
```

and where you want to stop and inspect: 

```
from trepan.api import debug; debug()
```

The more conventional approach is: 

```
import pdb; pdb.set_trace()
```

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I think I'm going to do other thing right now, that function is being called [here](https://github.com/mathics/Mathics/blob/master/mathics/format/svg.py#L239), and there we don't have a axis variable or something like that.

**Comment by rocky** [comment]
Ok - work on whatever suits you. The options dictionary is where you would add axis variables, and I am sure WL has defined a set of names  to use and default values for these.
