### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by szabop** [mathics/Mathics#481]
**Symptoms**
When I press the Save button in the save dialog, nothing happens.

**Other information**
- I just installed Mathics on OS X 10.11.6 (El Captan)
- In the browser network log I see an 500 internal sever error.
- In the console from where I started the maticsserver, I see a python trace complaining about a missing table:
- OperationalError: no such table: web_worksheet
- complete trace: [console_error.txt](https://github.com/mathics/Mathics/files/417270/console_error.txt)
- Table really seems to be missing from the SQLite DB:

```
Peters-MacBook-Pro:mathics-0.9 peti$ sqlite3 ~/.local/var/mathics/mathics.sqlite
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> .tables
auth_group                  auth_user_user_permissions
auth_group_permissions      django_content_type       
auth_permission             django_migrations         
auth_user                   django_session            
auth_user_groups            django_site               
sqlite> 
```

**Steps I did for installation**
- I downloaded version 0.9 from https://github.com/mathics/Mathics/releases/tag/v0.9
- unzipped
- from the unzipped directory ran: sudo python setup.py install

**Comment by jaycech3n** [comment]
This was reported in #382 and fixed in #473.
Alternatively run the command `python setup.py initialize`.

**Comment by szabop** [comment]
For the record: running `python setup.py initialize` from the command line in the directory where I initially downloaded and unzipped Mathics does not solve my issue.

The table `web_worksheet` is still not in the SQLLite DB, and saving still does not work.
[python_setup_initialize_output.txt](https://github.com/mathics/Mathics/files/430973/python_setup_initialize_output.txt)

**Comment by jaycech3n** [comment]
What version Django shows in the output of `pip freeze | grep Django`?
It needs to be version 1.8.*.

**Comment by jaycech3n** [comment]
Yes, apologies, before the patch the installer was also downloading a wrong version of Django, which I see is what you have from your error log.
Try uninstalling the current version 1.9 and installing version 1.8, then re-run the command and see if that fixes it.

**Comment by jaycech3n** [comment]
Yes, apologies, before the patch the installer was also downloading a wrong version of Django, which I see is what you have from your error log.
Try uninstalling the current version of Django (either with `pip uninstall django`, or if it wasn't installed with pip just delete the package directory) and install version 1.8 (`pip install django==1.8). Then re-run the initialize command and see if it fixes things.
